# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai_estimator',
                'doc_host': 'https://maxtheman.github.io',
                'git_url': 'https://github.com/maxtheman/ai_estimator',
                'lib_path': 'ai_estimator'},
  'syms': {'ai_estimator.core': {}}}
