# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['OPENAI_API_KEY']

# %% ../nbs/00_core.ipynb 4
OPENAI_API_KEY = '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'
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

