# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_server.ipynb.

# %% auto 0
__all__ = ['web_app', 'image', 'stub', 'run_server']

# %% ../nbs/01_server.ipynb 1
from .core import *
import modal
from fastapi import FastAPI
import gradio as gr
from gradio.routes import mount_gradio_app

from modal import asgi_app

# %% ../nbs/01_server.ipynb 2
web_app = FastAPI()
image = modal.Image.debian_slim().pip_install("pandas", "numpy", "langchain", "gradio","pydantic==2.3.0", "openai")
stub = modal.Stub("ai_estimator")
@stub.function(
    image=image,
    secret=modal.Secret.from_name("OPENAI_API_KEY"),
    concurrency_limit=1,
)
@asgi_app()
def run_server():
    return mount_gradio_app(
        app=web_app,
        blocks=gr.ChatInterface(gradio_agent, chatbot=gr.Chatbot(height=600)),
        path="/",
    )
    
